CREATE OR ALTER FUNCTION FIB_NUMBER (@number AS INTEGER)
RETURNS @numbers TABLE (Fibonacci VARCHAR(10))
AS
BEGIN
	DECLARE @a AS INTEGER = 1
	DECLARE @b AS INTEGER = 1
	DECLARE @c AS INTEGER = 0
	DECLARE @i AS INTEGER = 0 --iterator
	DECLARE @temp AS VARCHAR(5)
	WHILE (@i < @number)
		BEGIN
			SET @a = @b
			SET @b = @a + @c
			SET @c = @a
			SET @i = @i + 1
			INSERT INTO @numbers VALUES(CONVERT(VARCHAR(10), @a))
		END
	RETURN
END;

CREATE OR ALTER PROCEDURE FIBONACCI_WYWOLANIE (@number AS INTEGER) 
AS
BEGIN
	SELECT * FROM [dbo].[FIB_NUMBER](@number);
END;

EXEC firma.dbo.FIBONACCI_WYWOLANIE 10;